In [1]:
import numpy as np

In [57]:
def transform(X, a=1):
    x, y = X.shape
    res = np.zeros((x, y * 2))
    for row in range(x):
        res[row][0:y] = X[row][0:y]
        for i in range(y):
            if i % 2 == 0:
                res[row][-i - 1] = X[row][i] ** 3
            else:
                res[row][-i - 1] = a
    return res

In [58]:
# arr = np.random.randint(5, size=(2, 4))
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)
transform(arr)

[[1 2 3 4 5]
 [1 2 3 4 5]]


array([[  1.,   2.,   3.,   4.,   5., 125.,   1.,  27.,   1.,   1.],
       [  1.,   2.,   3.,   4.,   5., 125.,   1.,  27.,   1.,   1.]])