In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [5]:
iris_dataset = load_iris()
print(f"iris_dataset keys:\n{iris_dataset.keys()}")

iris_dataset keys:
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [10]:
# dataset description
print(iris_dataset["DESCR"][:250])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Informati


In [11]:
# dataset targets(classes)
print(iris_dataset["target_names"])

['setosa' 'versicolor' 'virginica']


In [12]:
# dataset features
print(iris_dataset["feature_names"])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


# dataset data: data.data and target

In [13]:
# dataset data: data.data and target
print(type(iris_dataset["data"]))

<class 'numpy.ndarray'>


In [14]:
# dataset shape: row, col
print(iris_dataset["data"].shape)

(150, 4)


In [15]:
# first 7 exemples 
print(iris_dataset["data"][:7])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]]


In [16]:
# dataset target
print(type(iris_dataset["target"]))

<class 'numpy.ndarray'>


In [17]:
# dataset shape: row, col(0)
print(iris_dataset["target"].shape)

(150,)


In [21]:
# dataset tagrets data
print(iris_dataset["target"][:70])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [22]:
# dataset target names
print(iris_dataset["target_names"])

['setosa' 'versicolor' 'virginica']
