In [1]:
import numpy as np

In [2]:
X = np.arange(64).reshape(8, 2, 4)

In [3]:
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [4]:
X.shape, len(X), X.size, X.ndim

((8, 2, 4), 8, 64, 3)

amounts on different axes

In [6]:
print(np.sum(X, axis=0), '\n') # 
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')
print(np.sum(X, axis=(1, 2)), '\n')

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 

[ 28  92 156 220 284 348 412 476] 



# Linear Algebra 

In [31]:
a = np.array([[2, 1], [2, 3]])
print(a)

[[2 1]
 [2 3]]


Determinant

In [14]:
np.linalg.det(a)

4.0

Inverse matrix

In [33]:
b = np.linalg.inv(a)
b

array([[ 0.75, -0.25],
       [-0.5 ,  0.5 ]])

In [17]:
print(a.dot(b))
print(b.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [22]:
# VERY BIG PROBLEM
c = np.array([[2, 1],[6, 3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
-3.330669073875464e-16


In [25]:
d = np.linalg.inv(c)
d

array([[-9.00719925e+15,  3.00239975e+15],
       [ 1.80143985e+16, -6.00479950e+15]])

Task

# Решение НЛУ

In [34]:
v = np.array([5, -10])
print(np.linalg.solve(a, v))
print(b.dot(v))

[ 6.25 -7.5 ]
[ 6.25 -7.5 ]


# Eigenvectors

In [36]:
# Eigennumbers, Eigenvectors
l, u = np.linalg.eig(a) 
l, u

(array([1., 4.]),
 array([[-0.70710678, -0.4472136 ],
        [ 0.70710678, -0.89442719]]))

In [40]:
l, u = np.linalg.eig(np.eye(3))
l, u

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

# Transposition

In [38]:
l, u = np.linalg.eig(a.T)
l, u

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))