In [30]:
import numpy as np

# 2 dim arrays

In [31]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [32]:
a.ndim, a. shape, len(a), a.size

(2, (2, 2), 2, 4)

In [33]:
a[1][1], a[1, 1] # indexin

(4, 4)

# Shape

In [34]:
b = np.arange(0, 20)
b.shape = (2, 10)   # b1.size must be equal to b2.size
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [35]:
b.ravel()   # Flattens the array into a one-dimensional

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
d = np.diag((np.array([1, 2, 3, 4])))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [40]:
a = -1 * np.eye(8)[::-1] + np.diag(np.arange(3, 27, 3))
a

array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  6.,  0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  9.,  0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0., 12., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1., 15.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0., 18.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0., 21.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0., 24.]])

# Matrix multiplication

In [41]:
a = 5 * np.ones((5, 5))
b = np.eye(5) + 1
a, b

(array([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]),
 array([[2., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1.],
        [1., 1., 2., 1., 1.],
        [1., 1., 1., 2., 1.],
        [1., 1., 1., 1., 2.]]))

In [42]:
%time
print(a * b, a @ b, a.dot(b), sep="\n\n")

Wall time: 0 ns
[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]]

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


# One index depends arrays

In [44]:
u = np.linspace(1, 2, 2)
v = np.linspace(4, 8, 3)
u, v

(array([1., 2.]), array([4., 6., 8.]))

In [45]:
x, y = np.meshgrid(u, v)
x, y

(array([[1., 2.],
        [1., 2.],
        [1., 2.]]),
 array([[4., 4.],
        [6., 6.],
        [8., 8.]]))

# Reshape

In [46]:
print(x.reshape(6))

[1. 2. 1. 2. 1. 2.]


In [47]:
is_prime = np.ones(100, dtype="bool")

In [48]:
is_prime[:2] = False

In [49]:
n_max = int(np.sqrt(len(is_prime)))
for i in range(2, n_max):
    is_prime[2 * i::i] = False

is_prime

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False])

# Masks

In [50]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


# Trace (след)

In [51]:
b = np.diag(a[a >= 10])
print(b)
print(b.trace())

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145
