# Too long

In [5]:
%%time
arr = []
a = 10 ** 7
for i in range(a):
    arr.append(a * 5)

Wall time: 1.82 s


In [6]:
%%time
def summ(a):
    ans = 0
    for i in a:
        ans += i
    return ans

print(summ(arr))

500000000000000
Wall time: 503 ms


# Quit fast (numpy)

In [ ]:
# !which python

# 1-dim array

the array data must be of the same type. Numpy has a hierarchy of data types

In [14]:
a = [1, 2, 32]
b = np.array(a, dtype="float64")
print(type(a), type(b))

<class 'list'> <class 'numpy.ndarray'>


In [18]:
s = np.array([1, 2, "a"]) # The whole array is str!
d = np.array([1, 2, 3])
d

array([1, 2, 3])

All methods of the class

In [19]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setitem__',
 '__setstate__',
 '__sub__',


In [21]:
arr = np.array([i for i in range(5)], dtype="int32")
arr.nbytes

20

Np can find your query(lookfor()). Documentation(?...). Function(...*?)

In [83]:
x = np.lookfor("mean value of array")

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.isrealobj
    Return True if x is a not complex type or an array of complex numbers.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Retur

In [84]:
?np.ma.mean

Signature:       np.ma.mean(a, *args, **params)
Type:            _frommethod
String form:     <numpy.ma.core._frommethod object at 0x0000015AB3459D00>
File:            c:\users\vadim\anaconda3\envs\learn_venv\lib\site-packages\numpy\ma\core.py
Docstring:      
mean(self, axis=None, dtype=None, out=None, keepdims=<no value>)

Returns the average of the array elements along given axis.

Masked entries are ignored, and result elements which are not
finite will be masked.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.ndarray.mean : corresponding function for ndarrays
numpy.mean : Equivalent function
numpy.ma.average : Weighted average.

Examples
--------
>>> a = np.ma.array([1,2,3], mask=[False, False, True])
>>> a
masked_array(data=[1, 2, --],
             mask=[False, False,  True],
       fill_value=999999)
>>> a.mean()
1.5
Class docstring:
Define functions from existing MaskedArray methods.

Parameters
----------
methodname : str
    Name of the method to tran

In [85]:
np.conca*?

np.concatenate

In [86]:
x = [[[1, 2, 3, 4],
      [2, 4, 8, 4],
      [1, 1, 1, 1]],
      [[1, 2, 3, 4],
       [4, 7, 5, 5],
       [7, 1, 5, 1]]]
arr = np.array(x)

In [87]:
print(len(arr), arr.size, arr.ndim, arr.shape, sep="\n")

2
24
3
(2, 3, 4)


In [88]:
a = np.array([1, 2, 3, 4])
a[0], a[-1]

(1, 4)

In [89]:
a[0] = 99
a

array([99,  2,  3,  4])

Don't iterate!  
(but if u want...)

In [90]:
for i in a:
    print(i)

99
2
3
4


In [91]:
# Default int32 (+-2.1e9)
arr = np.array([2, 3, 5, 7, -2000000000])
print(arr, arr.dtype, type(arr), arr.shape, arr.nbytes, sep="\n")

[          2           3           5           7 -2000000000]
int32
<class 'numpy.ndarray'>
(5,)
20


# Array creation

In [92]:
a = np.zeros(7)                 # float 
b = np.ones(7, dtype=np.int16)  # int16
print(a, b, sep="\n")

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


An array of zeros of the same size and DATA TYPE 

In [93]:
c = np.zeros_like(b) # int16, not float32
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

arrange like range

In [94]:
a = np.arange(1, 16, 4)
a

array([ 1,  5,  9, 13])

linspace between [a, b, points]

In [95]:
a = np.linspace(1, 15, 2)
b = np.linspace(4, 7, 10)
print(a, b, sep="\n")

[ 1. 15.]
[4.         4.33333333 4.66666667 5.         5.33333333 5.66666667
 6.         6.33333333 6.66666667 7.        ]


In [96]:
x = np.linspace(10, 32, 12)
x[1] - x[0]

2.0

Log scale (logspace)

In [97]:
# (degree1, degree2, elements) basis - 10
b = np.logspace(0, 3, 11)
b

array([   1.        ,    1.99526231,    3.98107171,    7.94328235,
         15.84893192,   31.6227766 ,   63.09573445,  125.89254118,
        251.18864315,  501.18723363, 1000.        ])

# Operations on arrays 
# element- by- element calculation (or scalar)

In [98]:
# The dimensions of the arrays must be the same
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a, b, sep="\n")
print(a + b, a - b, a * b, a / b, sep="\n")

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


In [99]:
a * 5, 10 + b

(array([ 15.,  30.,  45.,  60.,  75.,  90., 105., 120., 135., 150., 165.]),
 array([  8.,   6.,   4.,   2.,   0.,  -2.,  -4.,  -6.,  -8., -10., -12.]))

Yes, you really can raise a number to a power equal to an array or raise an array to a power

In [100]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a + b)
print((a + b) ** 2)
print(2 ** (a + b))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


# functions

In [101]:
type(np.cos)

numpy.ufunc

In [102]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [104]:
np.log(b)

C:\Users\Vadim\AppData\Local\Temp/ipykernel_2188/4200754868.py:1: RuntimeWarning: invalid value encountered in log
  np.log(b)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [106]:
print(a > b, a == b, a >= 10, sep="\n")

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


# Quantifiers of existence(any) and universality(all)

In [111]:
c = np.arange(0, 20)
print(np.any(c == 0.))
print(np.all(c == 0.))

True
False


# inplace operations

In [118]:
c = np.arange(0, 5, dtype="float64")
print(c)
c += np.sin(7)
print(c)
c *= 2
print(c)

[0. 1. 2. 3. 4.]
[0.6569866 1.6569866 2.6569866 3.6569866 4.6569866]
[1.3139732 3.3139732 5.3139732 7.3139732 9.3139732]


In [121]:
print(np.array([0, 2, -3]) / np.array([0, 0, 0]))

[ nan  inf -inf]


C:\Users\Vadim\AppData\Local\Temp/ipykernel_2188/3913445870.py:1: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([0, 2, -3]) / np.array([0, 0, 0]))
C:\Users\Vadim\AppData\Local\Temp/ipykernel_2188/3913445870.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array([0, 2, -3]) / np.array([0, 0, 0]))


# Constants

In [122]:
print(np.e, np.pi)

2.718281828459045 3.141592653589793


Cumulative sum

In [125]:
print(b)
print(b.cumsum())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]


sort arrays

In [130]:
a = np.array((1, 5, 45, 4, 12, 6, 0))
print(np.sort(a))   # Don't change array
print(a)
a.sort()            # Sort array
print(a)

[ 0  1  4  5  6 12 45]
[ 1  5 45  4 12  6  0]
[ 0  1  4  5  6 12 45]


Combining arrays (1-dim)

In [132]:
c = np.hstack((a, b, 5 * b))
c

array([ 0,  1,  4,  5,  6, 12, 45,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  5, 10, 15, 20, 25, 30,
       35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

splitting arrays

In [134]:
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(a)
print(x1)
print(x2)
print(x3)
print(x4)

[ 0  1  4  5  6 12 45]
[0 1 4]
[5 6]
[12]
[45]


append, delete, insert (NOT inplace functions)

In [135]:
print(np.delete(a, [2, 4, 1]))
print(a)

[ 0  5 12 45]
[ 0  1  4  5  6 12 45]


In [136]:
np.insert(a, 2, [77, 88])

array([ 0,  1, 77, 88,  4,  5,  6, 12, 45])

In [137]:
np.append(a, [1, 5, 9])

array([ 0,  1,  4,  5,  6, 12, 45,  1,  5,  9])

Indexing and slices

In [138]:
a[::-1] # reverse

array([45, 12,  6,  5,  4,  1,  0])

In [139]:
a[2:5] # slice

array([4, 5, 6])

In [140]:
b = a[0:6] # NOT A COPY
b[1] = -1000
print(a)

[    0 -1000     4     5     6    12    45]


In [143]:
a[1:6:3] = 99
a

array([ 0, 99,  4,  5, 99, 12, 45])

Copy array

In [144]:
b = a.copy()
b[2] = -50
a, b

(array([ 0, 99,  4,  5, 99, 12, 45]),
 array([  0,  99, -50,   5,  99,  12,  45]))

subarray

In [149]:
print(a[[5, 1, 3]]) # [[]] - important 

[12 99  5]


In [150]:
x = np.linspace(-4 * np.pi, 4 * np.pi, 100)
np.all((np.sin(x) ** 2 + np.cos(x) ** 2).round() == 1)

True